### ISSUE TITLE
Add Dribbble App in Apps section

### ISSUE THREAD

**Issue by catalinmiron** [ericvicenti/react-native-community#31]
Hi @ericvicenti,

I built a Dribbble app using React Native and i'm thinking if you can add it inside _Apps_ section.

Github link: https://github.com/catalinmiron/react-native-dribbble-app

Thanks,
[Catalin Miron](https://github.com/catalinmiron)

**Comment by ericvicenti** [comment]
Done. Thanks for your contribution!
